{%- if cookiecutter.publish_container -%}
name: Deply to GitHub Container Registry
on:
  push:
    tags:
      - v*.*

jobs:
 publish-container-image:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
      fetch-depth: 0       

   - name: Login to GitHub Container Registry
     uses: docker/login-action@v1
     with:
       registry: ghcr.io
       username: {% raw %}${{ github.actor }}{% endraw %}
       password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

   - name: Build the container image
     run: |
      docker build . --tag ghcr.io/{{ cookiecutter.docker_username }}/{{ cookiecutter.container_name }}:latest --tag ghcr.io/{{ cookiecutter.docker_username }}/{{ cookiecutter.container_name }}:${{github.ref_name}}
      docker push ghcr.io/{{ cookiecutter.docker_username }}/{{ cookiecutter.container_name }}:latest
      docker push ghcr.io/{{ cookiecutter.docker_username }}/{{ cookiecutter.container_name }}:${{github.ref_name}}
{%- else -%}

{% endif %}

